# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:15
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DDUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('drop_location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('qrcode', models.FileField(upload_to='qrcode')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='delivery.DDUser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to='delivery.DDUser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('location1', location_field.models.plain.PlainLocationField(max_length=63)),
                ('location2', location_field.models.plain.PlainLocationField(max_length=63)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.OrderAction')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='delivery.DDUser')),
                ('next_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_user', to='delivery.DDUser')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Order')),
            ],
        ),
        migrations.CreateModel(
            name='TrackStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.TrackStatus'),
        ),
        migrations.AddField(
            model_name='track',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='delivery.DDUser'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.OrderStatus'),
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.Order'),
        ),
        migrations.AddField(
            model_name='dduser',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.User_type'),
        ),
    ]
