# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20170424_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dduser',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='drop_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='location1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='location2',
            field=models.CharField(max_length=255),
        ),
    ]
