# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20170424_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
